name: vida
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  at_app_flutter: ^5.2.0
  at_client_mobile: ^3.2.12
  at_onboarding_flutter: ^6.1.5
  cupertino_icons: ^1.0.6
  fhir: ^0.11.5-dev2
  fhir_at_rest: ^0.11.4
  fhir_db: ^0.11.0-dev5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^11.1.4
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.7
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  intl: ^0.18.0
  uuid: ^4.1.0
